import type { Database } from "./db/database.types";

// ============================================================================
// BASE TYPES - Derived from database models
// ============================================================================

/**
 * Base flashcard row type from database
 */
type FlashcardRow = Database["public"]["Tables"]["flashcards"]["Row"];

/**
 * Base flashcard insert type from database
 */
type FlashcardInsert = Database["public"]["Tables"]["flashcards"]["Insert"];

/**
 * Base flashcard update type from database
 */
type FlashcardUpdate = Database["public"]["Tables"]["flashcards"]["Update"];

/**
 * Base generation session row type from database
 */
type GenerationSessionRow = Database["public"]["Tables"]["generation_sessions"]["Row"];

/**
 * Flashcard source enum type
 */
export type FlashcardSource = Database["public"]["Enums"]["flashcard_source"];

// ============================================================================
// PAGINATION DTOs
// ============================================================================

/**
 * Pagination metadata included in list responses
 */
export interface PaginationDTO {
  page: number;
  limit: number;
  total: number;
  total_pages: number;
}

// ============================================================================
// ERROR DTOs
// ============================================================================

/**
 * Detailed error information for a specific field
 */
export interface ErrorDetailDTO {
  field: string;
  message: string;
}

/**
 * Standard error response structure
 */
export interface ErrorDTO {
  error: {
    code:
      | "UNAUTHORIZED"
      | "FORBIDDEN"
      | "NOT_FOUND"
      | "VALIDATION_ERROR"
      | "UNPROCESSABLE_ENTITY"
      | "RATE_LIMITED"
      | "SERVICE_UNAVAILABLE"
      | "INTERNAL_ERROR";
    message: string;
    details?: ErrorDetailDTO[];
  };
}

// ============================================================================
// FLASHCARD DTOs
// ============================================================================

/**
 * Flashcard DTO - public representation of a flashcard (excludes user_id)
 * Used in GET /api/flashcards, GET /api/flashcards/:id, POST /api/flashcards responses
 */
export type FlashcardDTO = Omit<FlashcardRow, "user_id">;

/**
 * Query parameters for GET /api/flashcards
 */
export interface FlashcardsQueryParams {
  page?: number;
  limit?: number;
  sort?: "created_at" | "updated_at" | "next_review_date";
  order?: "asc" | "desc";
}

/**
 * Response for GET /api/flashcards - paginated list of flashcards
 */
export interface FlashcardsListResponseDTO {
  data: FlashcardDTO[];
  pagination: PaginationDTO;
}

// ============================================================================
// FLASHCARD COMMAND MODELS
// ============================================================================

/**
 * Command model for creating a single flashcard
 * Derived from database insert type, picking only user-provided fields
 */
export type CreateFlashcardCommand = Pick<FlashcardInsert, "front" | "back" | "source">;

/**
 * Command model for POST /api/flashcards - batch creation of flashcards
 */
export interface CreateFlashcardsCommand {
  flashcards: CreateFlashcardCommand[];
}

/**
 * Response for POST /api/flashcards - created flashcards
 */
export interface CreateFlashcardsResponseDTO {
  data: FlashcardDTO[];
}

/**
 * Command model for PUT /api/flashcards/:id - partial update of flashcard content
 * Only front and back can be updated by the user
 */
export type UpdateFlashcardCommand = Pick<FlashcardUpdate, "front" | "back">;

// ============================================================================
// AI GENERATION DTOs
// ============================================================================

/**
 * Command model for POST /api/generations - AI flashcard generation request
 */
export interface GenerateFlashcardsCommand {
  source_text: string;
}

/**
 * A single flashcard proposal generated by AI
 * Contains only front/back - no database metadata as proposals are not persisted
 */
export interface FlashcardProposalDTO {
  front: string;
  back: string;
}

/**
 * Response for POST /api/generations - AI generated flashcard proposals
 */
export interface GenerationResponseDTO {
  generation_id: string;
  proposals: FlashcardProposalDTO[];
  generated_count: number;
}

// ============================================================================
// STUDY SESSION DTOs
// ============================================================================

/**
 * Query parameters for GET /api/study-session
 */
export interface StudySessionQueryParams {
  limit?: number;
}

/**
 * Flashcard data for study session - subset of FlashcardDTO relevant for review
 */
export type StudySessionFlashcardDTO = Pick<
  FlashcardDTO,
  "id" | "front" | "back" | "ease_factor" | "interval" | "repetition_count"
>;

/**
 * Response for GET /api/study-session - flashcards due for review
 */
export interface StudySessionResponseDTO {
  data: StudySessionFlashcardDTO[];
  count: number;
  total_due: number;
}

/**
 * SM-2 rating scale: 0-5
 * 0 = Complete blackout
 * 1 = Incorrect, but recognized correct answer
 * 2 = Incorrect, but correct answer seemed easy
 * 3 = Correct with serious difficulty
 * 4 = Correct with some hesitation
 * 5 = Perfect response
 */
export type SM2Rating = 0 | 1 | 2 | 3 | 4 | 5;

/**
 * Command model for POST /api/study-session/review - record a flashcard review
 */
export interface ReviewFlashcardCommand {
  flashcard_id: string;
  rating: SM2Rating;
}

/**
 * Response for POST /api/study-session/review - updated SM-2 parameters
 */
export type ReviewResultDTO = Pick<
  FlashcardDTO,
  "id" | "ease_factor" | "interval" | "repetition_count" | "next_review_date" | "last_reviewed_at"
>;

// ============================================================================
// GENERATION SESSION DTOs (Statistics)
// ============================================================================

/**
 * Query parameters for GET /api/generation-sessions
 */
export interface GenerationSessionsQueryParams {
  page?: number;
  limit?: number;
}

/**
 * Generation session DTO - public representation (excludes user_id and source_text)
 * Used in GET /api/generation-sessions response
 */
export type GenerationSessionDTO = Omit<GenerationSessionRow, "user_id" | "source_text">;

/**
 * Summary statistics for generation sessions
 */
export interface GenerationSessionsSummaryDTO {
  total_generated: number;
  total_accepted: number;
  acceptance_rate: number;
}

/**
 * Response for GET /api/generation-sessions - paginated list with summary
 */
export interface GenerationSessionsListResponseDTO {
  data: GenerationSessionDTO[];
  pagination: PaginationDTO;
  summary: GenerationSessionsSummaryDTO;
}

/**
 * Command model for PATCH /api/generation-sessions/:id - update accepted count
 */
export interface UpdateGenerationSessionCommand {
  accepted_count: number;
}

